# Homework 1 
by Anthony Leouie Palmera

## Q1. Pandas Version

In [2]:
import pandas as pd
pd.__version__

'3.0.6'

## Getting the data
For this homework, we'll use the 2026 Car Fuel Efficiency dataset. Download it from [here](https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv).

In [5]:
data = pd.read_csv('data/car_fuel_efficiency_2026.csv')
data.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


## Q2. Records count
How many records are in the dataset?
- 5000
- 9000
- 10000
- 15000

In [7]:
data.shape

(10000, 11)

Answer: <b>10,000 records

## Q3. Fuel types
How many fuel types are presented in the dataset?
- 1
- 2
- 3
- 4

In [15]:
data['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [11]:
len(data['fuel_type'].unique())

3

Answer: <b> 3 Fuel Types

## Q4. Missing values
How many columns in the dataset have missing values?
- 0
- 1
- 2
- 3
- 4

In [16]:
data.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [26]:
missing_value = []

for i in data.columns:
    null_count = data[i].isnull().sum()
    if null_count > 0:
        missing_value.append((i, null_count))

print("Total columns with missing values:", len(missing_value))

Total columns with missing values: 2


Answer: <b> 2 Columns

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?
- 21.2
- 31.2
- 41.2
- 51.2

In [31]:
print(data[data['origin'] == 'Asia']['fuel_efficiency_mpg'].max())

41.2


Answer: <b> 41.2 Maximum Fuel Efficiency

## Q6. Median value of horsepower
1. Find the median value of the `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?
- Yes, it increased
- Yes, it decreased
- No

In [57]:
median_hp = data['horsepower'].median()
print(f"Median value of horsepower: {median_hp}")

Median value of horsepower: 254.0


In [73]:
mode_hp = data['horsepower'].mode()[0]
print(f"Most frequent value of horsepower: {mode_hp}")

Most frequent value of horsepower: 252.0


In [82]:
data['horsepower'] = data['horsepower'].fillna(mode_hp)
data['horsepower'].isnull().sum()

np.int64(0)

In [83]:
result_median_hp = data['horsepower'].median()
print(f"Median value of horsepower after filling missing values: {result_median_hp}")

Median value of horsepower after filling missing values: 252.0


Answer: <b> Yes, it decreased

## Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

- 0.0369
- 0.369
- 3.69
- 36.9

In [98]:
# 1. Select all the cars from Asia
# 2. Select only columns vehicle_weight and model_year
# 3. Select the first 7 values

asian_cars = data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)
print(asian_cars)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019


In [99]:
# 4. Get the underlying NumPy array. Let's call it X.

X = asian_cars.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [100]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [101]:
# 6. Invert XTX.

import numpy as np
XTX_inverted = np.linalg.inv(XTX)
XTX_inverted

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [102]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [103]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w = XTX_inverted.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [104]:
# 9. What's the sum of all the elements of the result?

print(f"Sum of all elements in w: {w.sum()}")

Sum of all elements in w: 0.36919696904925486


Answer: <b> 0.369

## Challenge Encountered:
- <b>[Q6. Median Value]</b> Missing values were not updating in the dataset, which was fixed by applying the fill operation directly to the column `data['horsepower'] = data['horsepower'].fillna(mode_hp)`